# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 516)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 50, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 0, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 50, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.x_value = QtWidgets.QLineEdit(self.centralwidget)
        self.x_value.setGeometry(QtCore.QRect(80, 150, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x_value.setFont(font)
        self.x_value.setObjectName("x_value")
        self.lam_value = QtWidgets.QLineEdit(self.centralwidget)
        self.lam_value.setGeometry(QtCore.QRect(270, 150, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lam_value.setFont(font)
        self.lam_value.setObjectName("lam_value")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 80, 391, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        self.a_value = QtWidgets.QLineEdit(self.centralwidget)
        self.a_value.setGeometry(QtCore.QRect(80, 50, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.a_value.setFont(font)
        self.a_value.setObjectName("a_value")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 150, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 180, 471, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.request_value = QtWidgets.QLineEdit(self.centralwidget)
        self.request_value.setGeometry(QtCore.QRect(270, 200, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.request_value.setFont(font)
        self.request_value.setObjectName("request_value")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 200, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-10, 230, 471, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.dt_value = QtWidgets.QLineEdit(self.centralwidget)
        self.dt_value.setGeometry(QtCore.QRect(270, 250, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dt_value.setFont(font)
        self.dt_value.setObjectName("dt_value")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 250, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 430, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 390, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(-10, 280, 471, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 300, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.process_btn = QtWidgets.QPushButton(self.centralwidget)
        self.process_btn.setGeometry(QtCore.QRect(320, 300, 111, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.process_btn.setFont(font)
        self.process_btn.setObjectName("process_btn")
        self.event_principle_line = QtWidgets.QLineEdit(self.centralwidget)
        self.event_principle_line.setGeometry(QtCore.QRect(270, 430, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.event_principle_line.setFont(font)
        self.event_principle_line.setObjectName("event_principle_line")
        self.dt_principle_line = QtWidgets.QLineEdit(self.centralwidget)
        self.dt_principle_line.setGeometry(QtCore.QRect(270, 390, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dt_principle_line.setFont(font)
        self.dt_principle_line.setObjectName("dt_principle_line")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(210, 150, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.b_value = QtWidgets.QLineEdit(self.centralwidget)
        self.b_value.setGeometry(QtCore.QRect(270, 50, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.b_value.setFont(font)
        self.b_value.setObjectName("b_value")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(-10, 80, 471, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(-10, 340, 471, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_5.setFont(font)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 350, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная работа №4"))
        self.label.setText(_translate("MainWindow", "a"))
        self.label_2.setText(_translate("MainWindow", "Генерация заявки (равномерный поток)"))
        self.label_3.setText(_translate("MainWindow", "b"))
        self.x_value.setText(_translate("MainWindow", "10"))
        self.lam_value.setText(_translate("MainWindow", "2"))
        self.label_4.setText(_translate("MainWindow", "Обработка заявки (нормальный поток)"))
        self.a_value.setText(_translate("MainWindow", "1"))
        self.label_5.setText(_translate("MainWindow", "x"))
        self.request_value.setText(_translate("MainWindow", "100"))
        self.label_6.setText(_translate("MainWindow", "Количество заявок"))
        self.dt_value.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "Delta t"))
        self.label_8.setText(_translate("MainWindow", "Событийный принцип"))
        self.label_9.setText(_translate("MainWindow", "Delta t"))
        self.label_10.setText(_translate("MainWindow", "Оптимальный размер очереди"))
        self.process_btn.setText(_translate("MainWindow", "Посчитать"))
        self.label_11.setText(_translate("MainWindow", "lam"))
        self.b_value.setText(_translate("MainWindow", "10"))
        self.label_12.setText(_translate("MainWindow", "Оптимальный размер очереди (результаты)"))

